#!/usr/bin/env bash
#
# Dev-stack bootstrap for the palworld-admin Pelican plugin.
#
#   ./dev/setup.sh                      panel only (plugin dev with mock API)
#   ./dev/setup.sh --with-wings        + wings daemon (real game servers; sudo)
#   ./dev/setup.sh --egg <file.yaml>    import a real Palworld egg instead of
#                                       the bundled placeholder
#   PANEL_PORT=8890 ./dev/setup.sh      use another port (default 8888)
#
# Creates dev/stack/ (gitignored) with a docker compose project "palworld-admin-dev":
# panel on localhost:$PANEL_PORT with THIS CHECKOUT bind-mounted as the live
# plugin, admin user, and a seeded node + "Palworld Dev" server so every plugin
# page is reachable. Idempotent - safe to re-run.

set -euo pipefail

PANEL_PORT="${PANEL_PORT:-8888}"
WITH_WINGS=0
EGG_FILE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --with-wings) WITH_WINGS=1 ;;
        --egg) EGG_FILE="$(realpath "$2")"; shift ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
STACK_DIR="${REPO_DIR}/dev/stack"
mkdir -p "${STACK_DIR}"

compose() { docker compose --project-directory "${STACK_DIR}" "$@"; }
artisan() { compose exec -T panel php artisan "$@"; }

command -v docker >/dev/null || { echo "docker is required" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "docker compose v2 is required" >&2; exit 1; }

# ---------------------------------------------------------------- compose file
cat > "${STACK_DIR}/compose.yml" <<EOF
# Generated by dev/setup.sh - do not edit, re-run the script instead.
name: palworld-admin-dev

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: unless-stopped
    ports:
      - "${PANEL_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
      - ${REPO_DIR}:/var/www/html/plugins/palworld-admin
    environment:
      XDG_DATA_HOME: /pelican-data
      APP_URL: "http://localhost:${PANEL_PORT}"
      APP_DEBUG: "true"
      APP_ENV: "local"
      # host-agnostic Caddy on :80 so wings can reach the panel as http://panel
      BEHIND_PROXY: "true"
      MAIL_DRIVER: "log"

  wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: unless-stopped
    profiles: ["wings"]
    ports:
      - "8080:8080"   # daemon api + browser websocket
      - "2022:2022"   # sftp
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /etc/pelican/:/etc/pelican/
      - /var/lib/pelican/:/var/lib/pelican/
      - /var/log/pelican/:/var/log/pelican/
      - /tmp/pelican/:/tmp/pelican/
      - /etc/ssl/certs:/etc/ssl/certs:ro

volumes:
  pelican-data:
  pelican-logs:
EOF

# --------------------------------------------------------------- placeholder egg
if [ -z "${EGG_FILE}" ]; then
    EGG_FILE="${STACK_DIR}/dev-egg.yaml"
    cat > "${EGG_FILE}" <<'EOF'
meta:
  version: PLCN_v3
  update_url: null
exported_at: '2026-01-01T00:00:00+00:00'
name: 'Palworld (Dev Placeholder)'
author: dev@palworld-admin.local
uuid: 5d3c0d55-70de-4b1c-9d3e-0de6a8f00dd1
description: |-
  Placeholder egg for palworld-admin plugin development. Contains the variables
  the plugin expects but does not run a real game server (startup just idles).
  Import a real Palworld egg for in-game testing.
icon: null
tags:
  - palworld
features: []
docker_images:
  'SteamCMD Debian': 'ghcr.io/parkervcp/steamcmd:debian'
file_denylist: []
startup_commands:
  Default: 'echo dev-egg-ready && sleep infinity'
config:
  files: {  }
  startup:
    done: 'dev-egg-ready'
  logs: {  }
  stop: '^C'
scripts:
  installation:
    script: |-
      #!/bin/bash
      echo "dev placeholder egg - nothing to install"
    container: 'ghcr.io/parkervcp/installers:debian'
    entrypoint: bash
variables:
  -
    name: 'Admin Password'
    description: 'REST API / RCON admin password.'
    env_variable: ADMIN_PASSWORD
    default_value: devpassword
    user_viewable: true
    user_editable: true
    rules:
      - required
      - string
    sort: 1
  -
    name: 'REST API Port'
    description: 'Port of the official REST API.'
    env_variable: REST_API_PORT
    default_value: 8212
    user_viewable: true
    user_editable: false
    rules:
      - required
      - numeric
    sort: 2
  -
    name: 'Enable REST API'
    description: 'Applied to PalWorldSettings.ini by the config parser.'
    env_variable: REST_API_ENABLED
    default_value: 'True'
    user_viewable: true
    user_editable: true
    rules:
      - required
      - string
      - 'in:True,False'
    sort: 3
EOF
fi

# ------------------------------------------------------------------- seed script
cat > "${STACK_DIR}/seed.php" <<'EOF'
<?php
// Idempotent dev seed: egg + node + allocations + "Palworld Dev" server.
use App\Enums\EggFormat;
use App\Models\Allocation;
use App\Models\Egg;
use App\Models\Node;
use App\Models\Server;
use App\Models\User;
use App\Services\Eggs\Sharing\EggImporterService;
use Illuminate\Support\Str;

$eggYaml = file_get_contents('/tmp/dev-egg.yaml');
$existingEgg = Egg::query()->where('name', 'like', '%palworld%')->first();
$egg = app(EggImporterService::class)->fromContent($eggYaml, EggFormat::YAML, $existingEgg);
echo "egg: {$egg->name}\n";

$node = Node::first();
if (!$node) {
    $node = new Node();
    $node->forceFill([
        'uuid' => Str::uuid()->toString(),
        'name' => 'dev-node',
        'fqdn' => 'host.docker.internal',
        'scheme' => 'http',
        'public' => true,
        'memory' => 0, 'memory_overallocate' => 0,
        'disk' => 0, 'disk_overallocate' => 0,
        'cpu' => 0, 'cpu_overallocate' => 0,
        'daemon_token_id' => Str::random(16),
        'daemon_token' => Str::random(64),
        'daemon_listen' => 8080, 'daemon_sftp' => 2022, 'daemon_connect' => 8080,
        'daemon_base' => '/var/lib/pelican/volumes',
    ])->saveQuietly();
    echo "node: created\n";
}

if (Server::query()->count() > 0) {
    echo "server: already seeded\n";
    return;
}

$allocation = function (int $port, ?string $notes = null) use ($node): Allocation {
    $existing = Allocation::query()->where('node_id', $node->id)->where('port', $port)->first();
    if ($existing) {
        return $existing;
    }
    $alloc = new Allocation();
    $alloc->forceFill(['node_id' => $node->id, 'ip' => '0.0.0.0', 'port' => $port, 'notes' => $notes])->saveQuietly();

    return $alloc;
};
$game = $allocation(8211);
$rest = $allocation(8212, 'Palworld REST API');

$owner = User::query()->orderBy('id')->first();

$server = new Server();
$server->forceFill([
    'uuid' => Str::uuid()->toString(),
    'uuid_short' => substr(str_replace('-', '', Str::uuid()->toString()), 0, 8),
    'node_id' => $node->id,
    'name' => 'Palworld Dev',
    'description' => 'palworld-admin plugin dev server',
    'owner_id' => $owner->id,
    'memory' => 0, 'swap' => 0, 'disk' => 0, 'io' => 500, 'cpu' => 0,
    'oom_killer' => false,
    'allocation_id' => $game->id,
    'egg_id' => $egg->id,
    'startup' => $egg->startup_commands['Default'] ?? array_values($egg->startup_commands)[0],
    'image' => array_values($egg->docker_images)[0],
    'status' => null,
    'installed_at' => now(),
])->saveQuietly();

$game->forceFill(['server_id' => $server->id])->saveQuietly();
$rest->forceFill(['server_id' => $server->id])->saveQuietly();

$server->ensureVariablesExist();
$server->serverVariables()
    ->whereHas('variable', fn ($q) => $q->where('env_variable', 'ADMIN_PASSWORD'))
    ->update(['variable_value' => 'devpassword']);

echo "server: {$server->uuid_short} (Palworld Dev)\n";
EOF

# --------------------------------------------------------------------- bring up
echo "==> starting panel (localhost:${PANEL_PORT}) ..."
compose up -d panel

# The panel image only runs migrations when APP_INSTALLED=true; a fresh volume
# gets APP_INSTALLED=false and expects the web installer, so the database would
# never be created. Migrate ourselves and mark the panel installed.
echo -n "==> bootstrapping database (bypasses the web installer)"
booted=0
for _ in $(seq 1 60); do
    if compose exec -T panel grep -q '^APP_INSTALLED=' /pelican-data/.env 2>/dev/null; then
        booted=1
        break
    fi
    echo -n .
    sleep 2
done
echo
[ "${booted}" = "1" ] || { echo "panel container did not boot - check: (cd dev/stack && docker compose logs panel)" >&2; exit 1; }
if ! compose exec -T panel grep -q '^APP_INSTALLED=true' /pelican-data/.env; then
    artisan migrate --force >/dev/null
    compose exec -T panel sed -i 's/^APP_INSTALLED=false/APP_INSTALLED=true/' /pelican-data/.env
fi

echo -n "==> waiting for panel"
ready=0
for _ in $(seq 1 60); do
    if curl -sf -o /dev/null "http://localhost:${PANEL_PORT}/login" \
        && artisan tinker --execute='echo Illuminate\Support\Facades\Schema::hasTable("users") ? "ready" : "not-yet";' 2>/dev/null | grep -q ready; then
        ready=1
        break
    fi
    echo -n .
    sleep 2
done
echo
[ "${ready}" = "1" ] || { echo "panel did not come up - check: (cd dev/stack && docker compose logs panel)" >&2; exit 1; }

echo "==> creating admin user (admin / palworld-dev) ..."
for _ in 1 2 3; do
    artisan p:user:make --email=dev@palworld-admin.local --username=admin --password=palworld-dev --admin=1 -n >/dev/null 2>&1 && break
    sleep 3
done
USERS=$(artisan tinker --execute='echo App\Models\User::query()->count();' | tr -cd '0-9')
[ "${USERS:-0}" -ge 1 ] || { echo "admin user creation failed - run manually: (cd dev/stack && docker compose exec panel php artisan p:user:make)" >&2; exit 1; }

echo "==> installing plugin + migrations ..."
# the panel writes install status into plugin.json - make sure it can
chmod a+w "${REPO_DIR}/plugin.json"
artisan p:plugin:install palworld-admin -n >/dev/null 2>&1 || true
artisan migrate --force >/dev/null
artisan filament:optimize-clear >/dev/null 2>&1 || true

echo "==> seeding egg / node / dev server ..."
compose cp "${EGG_FILE}" panel:/tmp/dev-egg.yaml
compose cp "${STACK_DIR}/seed.php" panel:/tmp/dev-seed.php
artisan tinker /tmp/dev-seed.php
SERVERS=$(artisan tinker --execute='echo App\Models\Server::query()->count();' | tr -cd '0-9')
[ "${SERVERS:-0}" -ge 1 ] || { echo "seeding failed - inspect: (cd dev/stack && docker compose exec panel php artisan tinker /tmp/dev-seed.php)" >&2; exit 1; }

# ------------------------------------------------------------------------ wings
if [ "${WITH_WINGS}" = "1" ]; then
    echo "==> setting up wings (sudo needed for /etc/pelican & friends) ..."
    sudo mkdir -p /etc/pelican /var/lib/pelican /var/log/pelican /tmp/pelican
    artisan p:node:configuration 1 \
        | sed "s|remote: '.*'|remote: 'http://panel'|" > "${STACK_DIR}/wings-config.yml"
    printf "allowed_origins:\n  - 'http://localhost:%s'\n" "${PANEL_PORT}" >> "${STACK_DIR}/wings-config.yml"
    sudo cp "${STACK_DIR}/wings-config.yml" /etc/pelican/config.yml
    compose --profile wings up -d wings
    echo "    wings up - reinstall the dev server in the panel to provision it"
fi

cat <<EOF

============================================================
 Dev stack ready.

   Panel:    http://localhost:${PANEL_PORT}   (admin / palworld-dev)
   Server:   "Palworld Dev" -> Palworld Players / Bans / Settings tabs
   Mock API: python3 dev/mock-palworld-api.py   (fixture players on :8212)

   Stack dir: dev/stack  (docker compose from there; 'down -v' wipes data)
============================================================
EOF
